apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vote-helm.fullname" . }}
  labels:
    {{- include "vote-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vote-helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      lablename: vote
  template:
    metadata:
      labels:
        {{- include "vote-helm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "vote-helm.serviceAccountName" . }}
      containers:
        - name: {{ include "vote-helm.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
