apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "result-helm.name" . }}
  labels:
    {{- include "result-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "result-helm.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "result-helm.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "result-helm.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}