apiVersion: v1
kind: Service
metadata:
  name: {{ include "result-helm.name" . }}
  labels:
    {{- include "result-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "result-helm.labels" . | nindent 4 }}
  ports:
    - name: result-service
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
