apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker-helm.fullname" . }}
  labels:
    {{- include "worker-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "worker-helm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "worker-helm.name" . }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
